### ISSUE TITLE
Distance ring issue

### ISSUE THREAD

**Issue by Markyp464** [carlcodling/targific#1]
Hi,
I noticed an issue with the distance ring. Mine is set to a daily goal of 5 miles but the ring doesn’t close until about 8 miles. I’m wondering if this is something to do with the metric/imperial conversion. 
Thanks for your help. 
![image](https://user-images.githubusercontent.com/90987964/133908524-73704cd2-63c3-4e24-95a9-588defbd40dc.jpg)

**Comment by carlcodling** [comment]
Thanks, I think I can see what's causing this. Should have an update pushed to the fitbit gallery in the next few days.

**Comment by Markyp464** [comment]
Hi,

That’s brilliant, thank you.

I really like this Clock face, thank you for developing it.  I hope reporting the issue was useful.

Best regards,
Mark Powell
________________________________

**Comment by carlcodling** [comment]
Very useful thanks! 

Glad you like the clock face, I submitted an update for it to fitbit this morning but it can sometimes take a few days for them to review and accept the changes.

**Comment by Markyp464** [comment]
I received the update about 13:00 today. You’ve nailed it! Job done. Thank you. 😊[Image.jpeg]

Best regards,
Mark Powell
________________________________
