### ISSUE TITLE
Ability to select Kilojoules for Calories ring

### ISSUE THREAD

**Issue by Graekynn** [carlcodling/targific#3]
Hi, this is more of a request than an issue, just wondering if a setting can be added to select between calories or kilojoules for the 'energy' ring and whether this ring can represent your daily calorie or kilojoule budget? This is by far my favourite face for quick info and being able to choose between those values would be perfect. Many thanks!

**Comment by carlcodling** [comment]
Hi there, thanks for the suggestion. That sounds pretty simple to implement, I'll try to get it pushed out in an update over the next few days.

**Comment by carlcodling** [comment]
Hello again, I've just added an option to switch between calories and kJ. The update has been submitted to fitbit for review which usually takes a couple of days. Hopefully you should get an update with the changes by the end of the week.

**Comment by Graekynn** [comment]
That works perfectly, thank you so much for making that change!
